apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pcap-exporter
  namespace: kube-system
  labels:
    app: pcap-exporter
spec:
  selector:
    matchLabels:
      app: pcap-exporter
  template:
    metadata:
      labels:
        app: pcap-exporter
    spec:
      hostNetwork: true
      containers:
        - name: pcap-exporter
          image: lmarszal/pcap_exporter:0.2
          imagePullPolicy: Always
          command: [ "/app/pcap_exporter" ]
          args: [ "-f", "port 8472" ]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pcap-exporter
  name: pcap-exporter-prometheus-discovery
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9999
      protocol: TCP
  selector:
    app: pcap-exporter
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: pcap-exporter
  name: pcap-exporter
  namespace: kube-system
spec:
  endpoints:
    - interval: 5s
      metricRelabelings:
      - sourceLabels: [ instance ]
        targetLabel: instance
      port: http-metrics
      scheme: http
  jobLabel: pcap-exporter
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: pcap-exporter